apiVersion: aws.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-aws-2
  namespace: default
  annotations:
    uptest.upbound.io/post-assert-hook: testhooks/delete-release.sh
spec:
  forProvider:
    region: us-west-2
  id: platform-ref-aws-2
  parameters:
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: platform-ref-aws-kubeconfig-2
