apiVersion: aws.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: upbound-ref-cluster-1
  namespace: default
  annotations:
    uptest.upbound.io/post-assert-hook: testhooks/delete-release.sh
spec:
  id: platform-ref-aws
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: upbound-ref-kubeconfig-1
