apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgDHNoTbbV0dl4Qe0jolXggDgcZ7D8UcSvwvGrCnoOnU4BrZbdzqlLGde3DXWtidmBN3KaI1tI0i6hAbif1Mri1a+4Ck1/lKVSKu/jeC5o9gk0iljljs8iupitp+d+iefrN/EL2j/uO3N1CDlQMM67P3fSTYrZMN8LrtjiAmDvQFSoQMVfb6/MM0edrz5znKYblsfhGLlDCrIv9PGhe72l4XIyg0xfqggWuhj9mMR1ZGpB6uueP4JFfTmo0yHI+6XuFXfUMqsmF75tqzglOlG5TECp2OnB4d3OUCzUqcrzyiqLgDoBEoT9vxCgByIScKZ4sUVbVeUteCFbhNcPM8kYLKjht2PM2QwiJrzO0pz5dCwUHKQAZ57zjM87wjUktaSYR1PlzTSueYQIgqXf+8n/4ebh+2jTlpHTpyxJXFLZ9P2OSdebFIPov7+ZmGNLi9T+MSEdWz1OjjweeU34JZMAeZBlJlpqq6w0g1iGeQCCEJKeXftvpOQCmDV1WNEy0BErL1GhYDSI1eZmGys4/FDAaPL++qqs50/2axwXHtWiQFkZqJ3LiocyVjuuUyeIuwwrBQQuHqOZnCqgPoq9kU/a0hsaOZI7nyTKnawfyTTFQwbXWod5VROKODMi9hUeMEtpzWCEubTX5oGT4z3NDY8kmUvNPO6woI+7FexGRixjPrcaUykNeZIV49/kjn4xzTAaeTb9xLygE2MvWDwd870MKclFKTWXiADUoFk5YMf4iyx3jUP0BJyGES/P5IVTg0RaJm0LkBDp3wN3XLZ1/3s27Lw8VgaQTKJjRIeU0MPBSfSKsl1DyI+UeXkk/jG2oesOy9f4JD5qKE8GLDTSBaIP03iBQ6qA==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system
    type: Opaque
